GET http://localhost:8080/api/books

###

GET http://localhost:8080/a

###
POST http://localhost:8080/api/books
Content-Type: application/json

{
    "title": "1",
    "description": "2",
    "comment": "3",
    "rating": 4
}

###

PATCH http://localhost:8080/api/books/633471d481d8ae4ba04fbca8
Content-Type: application/json

{
    "rating": 5
}

###

DELETE http://localhost:8080/api/books/6